#ifndef ITEM_WEAPON_LOCKER_SHARED_H
#define ITEM_WEAPON_LOCKER_SHARED_H

#define WEAPON_LOCKER_DEFAULT_SCRIPT "scripts/weapon_locker.txt"
#define WEAPON_LOCKER_MAX_WEAPONS 128
#define WEAPON_LOCKER_MAX_CATEGORIES 32
#define WEAPON_LOCKER_MAX_NAME 64

#define WEAPON_LOCKER_OPEN_MSG "WeaponLocker_Open"

#endif